# Site settings
title: Enabled - iOS, Android, App, Website Developers, Adelaide
description: > # Default meta description
  Digital media agency developing iPhone, Android &amp; mobile applications, 
  websites with video &amp; search engine optimisation, touch signage, 
  interactive digital media.
keywords: > # Default meta keywords
  Enabled, Enabled Solutions, Adelaide, Australia, mobile, mobile applications, iPhone developers,iPad developers,cross platform developers, Android developers, ios developers, Adelaide, digital media, websites, CMS websites, design, branding, digital design, video, motion, touch

url: "https://enabledhq.github.io"

# Build settings
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: 'https://enabledhq.github.io'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"      
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "date"
        field:
          element: "text"
          label: "Publish Date"
          value: CURRENT_DATETIME          
          placeholder: "YYYY-MM-DD HH:MM"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "author"
        field:
          element: "select"
          label: "Author"
          placeholder: "Choose author"
          value: grant
          options:
            - name: "Linh Dao"
              value: linh            
            - name: "Grant Hull"
              value: grant
            - name: "Dylan Sale"
              value: dylan         
      - name: "main-category"
        field:
          element: "select"
          label: "Main Category"
          placeholder: "Choose categories"
          value: technology
          options:
            - name: "Innovation"
              value: innovation
            - name: "Technology"
              value: technology
            - name: "User Experience"
              value: ux
            - name: "Entrepreneurship"
              value: entrepreneurship
      - name: "categories"
        field:
          element: "multiselect"
          label: "Additional Categories"
          placeholder: "Choose categories"
          value: technology
          options:
            - name: "Innovation"
              value: innovation
            - name: "Technology"
              value: technology
            - name: "User Experience"
              value: ux
            - name: "Entrepreneurship"
              value: entrepreneurship
      - name: "meta-keywords"
        field:
          element: "text"
          label: "Keywords"
          placeholder: "Enter Keywords"
      - name: "hero-banner"
        field:
          element: "text"
          label: "Hero Banner"
          placeholder: "Enter image URL (e.g., images/my_image.jpg)"
      - name: "thumbnail-image"
        field:
          element: "text"
          label: "Thumbnail"
          placeholder: "Enter image URL (e.g., images/my_image.jpg)"