# Site settings
title: Blog - Stories on Innovation, Technology & Design
description: > # Default meta description
  Our musings as we help businesses make sense of digital disruption and build innovative enablers including software, UX, product development, mobile, IoT.
keywords: > # Default meta keywords
  Design thinking services, digital innovation, IoT, software development, design thinking consulting, digital strategy consulting adelaide, innovation strategy consulting, innovation consulting services, design and innovation consulting firm, digital disruption, app development adelaide

url: "http://blog.enabled.com.au"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed

permalink: /:title/

prose:
  media: 'images'
  ignore: ['_includes', '_layouts', '_sass', '.gitignore', 'CNAME']
  metadata:    
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "date"
        field:
          element: "text"
          label: "Publish Date"
          value: CURRENT_DATETIME          
          placeholder: "YYYY-MM-DD HH:MM"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "textarea"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "meta-description"
        field:
          element: "textarea"
          label: "Meta Description"
          placeholder: "Enter Meta Description (for search results)"
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Summary (RSS/enabled.com.au)"
          placeholder: "Enter Summary/Excerpt (for enabled.com.au and RSS feed)"
      - name: "author"
        field:
          element: "multiselect"
          label: "Authors"
          placeholder: "Choose authors"
          value: linh
          options:
            - name: "Linh Dao"
              value: linh            
            - name: "Grant Hull"
              value: grant
            - name: "Dylan Sale"
              value: dylan
            - name: "Josh Rogers"
              value: josh
            - name: "Simeon SaÃ«ns"
              value: simeon
            - name: "Colin Capurso"
              value: colin
            - name: "Jarrod Swift"
              value: jarrod
            - name: "James Hubbard"
              value: james 
            - name: "John Smith"
              value: john
      - name: "main-category"
        field:
          element: "select"
          label: "Main Category"
          placeholder: "Choose categories"
          options:
            - name: "Innovation"
              value: innovation
            - name: "Technology"
              value: technology
            - name: "User Experience"
              value: ux
            - name: "Entrepreneurship"
              value: entrepreneurship
            - name: "General News"
              value: news              
      - name: "categories"
        field:
          element: "multiselect"
          label: "Additional Categories"
          placeholder: "Choose categories"
          options:
            - name: "Innovation"
              value: innovation
            - name: "Technology"
              value: technology
            - name: "User Experience"
              value: ux
            - name: "Entrepreneurship"
              value: entrepreneurship
            - name: "General News"
              value: news              
      - name: "short-link"
        field:
          element: "text"
          label: "Short Link"
          placeholder: "Enter short link"
      - name: "meta-keywords"
        field:
          element: "text"
          label: "Keywords"
          placeholder: "Enter Keywords"
      - name: "hero-banner"
        field:
          element: "text"
          label: "Hero Banner"
          placeholder: "Enter image URL (e.g., images/my_image.jpg)"
      - name: "image"
        field:
          element: "text"
          label: "Thumbnail"
          placeholder: "Enter image URL (e.g., images/my_image.jpg)"
